plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
    id 'multiloader-library'
}

base {
    archivesName = 'narrativecraft-api'
}

legacyForge {
    mcpVersion = minecraft_version
}

configurations {
    apiJava {
        canBeResolved = false
        canBeConsumed = true
    }
    apiResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    apiJava sourceSets.main.java.sourceDirectories.singleFile
    apiResources sourceSets.main.resources.sourceDirectories.singleFile
}

